backend:
  name: github
  repo: elibenton/personal-website
  branch: version-2

media_folder: content/images
public_folder: static

publish_mode: editorial_workflow

site_url: https://elibenton.co

collections:
  - name: writing
    label: Writing
    folder: content/writing
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: city, label: City }
      - { name: country, label: Country }

      - { name: description, label: Description, widget: text }

      - { name: categories, label: Categories, widget: list }
      - { name: tags, label: Tags, widget: list }

      - { name: audio-file, label: Audio File, widget: file, required: false }
      - { name: publication, label: Publication, required: false }

      - { name: body, label: Body, widget: markdown }
