backend:
  name: github
  repo: elibenton/personal-website
  branch: version-2

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: city, label: City }
      - { name: country, label: Country }
      - { name: description, label: description, widget: text }
      - { name: tags, label: Tags, widget: list }
      - { name: types, label: Types }
      - { name: color, label: Color }
      - { name: body, label: Body, widget: markdown }
